#!/usr/bin/env bash
set -Eeuo pipefail

APP_NAME="ubuntuAV"
APP_VERSION="1.2.1"
MANAGED_MARK="# ubuntuAV managed"
EU_COUNTRIES="AT BE BG HR CY CZ DK EE FI FR DE GR HU IE IT LV LT LU MT NL PL PT RO SK SI ES SE"
ACTION_LOG_DIR="${PWD}/ubuntuav-logs"
ACTION_LOG_FILE=""

C_RESET=$'\033[0m'
C_BOLD=$'\033[1m'
C_DIM=$'\033[2m'
C_BLUE=$'\033[38;5;39m'
C_CYAN=$'\033[38;5;45m'
C_GREEN=$'\033[38;5;70m'
C_YELLOW=$'\033[38;5;220m'
C_RED=$'\033[38;5;203m'
C_WHITE=$'\033[97m'
C_SELECT=$'\033[48;5;25m'
HEADER_LINES=6

cecho() { printf '%b%s%b\n' "$1" "$2" "$C_RESET"; }
bold() { cecho "$C_BOLD$C_WHITE" "$*"; }
info() { printf '%b[INFO]%b %s\n' "$C_GREEN" "$C_RESET" "$*"; }
warn() { printf '%b[WARN]%b %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
err() { printf '%b[ERR ]%b %s\n' "$C_RED" "$C_RESET" "$*" >&2; }

term_cols() {
  if command -v tput >/dev/null 2>&1; then
    tput cols 2>/dev/null || printf '80\n'
  else
    printf '80\n'
  fi
}

term_lines() {
  if command -v tput >/dev/null 2>&1; then
    tput lines 2>/dev/null || printf '24\n'
  else
    printf '24\n'
  fi
}

timestamp() { date +%Y%m%d-%H%M%S; }

init_action_log() {
  mkdir -p "$ACTION_LOG_DIR"
  ACTION_LOG_FILE="$ACTION_LOG_DIR/ubuntuav-$(hostname 2>/dev/null || printf server)-$(timestamp).sh"
  {
    printf '#!/usr/bin/env bash\n'
    printf 'set -Eeuo pipefail\n\n'
    printf '# Generated by %s v%s on %s\n' "$APP_NAME" "$APP_VERSION" "$(date -Is)"
    printf '# Review before replay on another server.\n\n'
  } > "$ACTION_LOG_FILE"
  chmod 700 "$ACTION_LOG_FILE"
}

log_action() {
  [ -n "$ACTION_LOG_FILE" ] || return 0
  printf '%s\n' "$*" >> "$ACTION_LOG_FILE"
}

log_comment() {
  [ -n "$ACTION_LOG_FILE" ] || return 0
  printf '\n# %s\n' "$*" >> "$ACTION_LOG_FILE"
}

log_write_file() {
  local file="$1" content="$2"
  [ -n "$ACTION_LOG_FILE" ] || return 0
  {
    printf "sudo tee %s >/dev/null <<'EOF'\n" "$file"
    printf '%s\n' "$content"
    printf 'EOF\n'
  } >> "$ACTION_LOG_FILE"
}

log_append_file() {
  local file="$1" content="$2"
  [ -n "$ACTION_LOG_FILE" ] || return 0
  {
    printf "sudo tee -a %s >/dev/null <<'EOF'\n" "$file"
    printf '%s\n' "$content"
    printf 'EOF\n'
  } >> "$ACTION_LOG_FILE"
}

is_root() { [ "${EUID:-$(id -u)}" -eq 0 ]; }

run_root() {
  if is_root; then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "$@"
  else
    err "Ova akcija treba root prava, a sudo nije dostupan."
    return 1
  fi
}

run_user() {
  local user="$1"
  shift
  if command -v sudo >/dev/null 2>&1; then
    sudo -u "$user" "$@"
  else
    err "Ova akcija treba sudo za korisnika $user."
    return 1
  fi
}

ui_cleanup() {
  if command -v tput >/dev/null 2>&1; then
    tput csr 0 "$(($(term_lines) - 1))" 2>/dev/null || true
    tput sgr0 2>/dev/null || true
    tput cnorm 2>/dev/null || true
  fi
}

trap ui_cleanup EXIT

pause() {
  printf '\n%b' "$C_DIM" >&2
  read -r -p "Enter za nastavak..." _
  printf '%b' "$C_RESET" >&2
}

confirm() {
  local prompt="${1:-Nastaviti?}"
  local answer
  printf '%b' "$C_CYAN" >&2
  read -r -p "$prompt [y/N]: " answer
  printf '%b' "$C_RESET" >&2
  case "${answer,,}" in
    y|yes|da|d) return 0 ;;
    *) return 1 ;;
  esac
}

prompt_value() {
  local prompt="$1"
  local value
  printf '%b' "$C_CYAN" >&2
  read -r -p "$prompt: " value
  printf '%b' "$C_RESET" >&2
  printf '%s\n' "$value"
}

repeat_char() {
  local char="$1" count="$2"
  printf '%*s' "$count" '' | tr ' ' "$char"
}

menu_badge() {
  local label="$1" count="${2:-0}"
  if [ "$count" -gt 0 ]; then
    printf '%s %b(%s)%b\n' "$label" "$C_RED$C_BOLD" "$count" "$C_RESET"
  else
    printf '%s\n' "$label"
  fi
}

safe_head() { "$@" 2>/dev/null | head -n 1 || true; }

package_version() {
  local pkg="$1"
  dpkg-query -W -f='${Version}' "$pkg" 2>/dev/null || printf -- '-'
}

command_version() {
  local cmd="$1"
  shift
  if command -v "$cmd" >/dev/null 2>&1; then
    "$cmd" "$@" 2>&1 | head -n 1
  else
    printf -- '-'
  fi
}

python_version_label() {
  if command -v python3 >/dev/null 2>&1; then
    python3 --version 2>/dev/null | awk '{print $2}'
  else
    printf -- '-'
  fi
}

primary_ip() {
  ip -4 route get 1.1.1.1 2>/dev/null | awk '/src/ {for (i=1; i<=NF; i++) if ($i=="src") {print $(i+1); exit}}'
}

gateway_ip() {
  ip route 2>/dev/null | awk '/default/ {print $3; exit}'
}

os_label() {
  if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    printf '%s\n' "${PRETTY_NAME:-${NAME:-Ubuntu}}"
  else
    printf 'Ubuntu/Debian\n'
  fi
}

render_header() {
  local cols line host ip_addr gate os_name ssh_v nginx_v pg_v py_v
  cols="$(term_cols)"
  line="$(repeat_char '=' "$cols")"
  host="$(hostname 2>/dev/null || printf '-')"
  ip_addr="$(primary_ip)"
  gate="$(gateway_ip)"
  os_name="$(os_label)"
  ssh_v="$(package_version openssh-server)"
  nginx_v="$(package_version nginx)"
  pg_v="$(package_version postgresql)"
  py_v="$(python_version_label)"

  printf '%b%s%b\n' "$C_BLUE$C_BOLD" "$line" "$C_RESET"
  printf '%b%s%b %bv%s%b   %bHost:%b %s   %bIP:%b %s\n' \
    "$C_BLUE$C_BOLD" "$APP_NAME" "$C_RESET" "$C_DIM" "$APP_VERSION" "$C_RESET" \
    "$C_CYAN" "$C_RESET" "$host" "$C_CYAN" "$C_RESET" "${ip_addr:-"-"}"
  printf '%bOS:%b %s   %bGateway:%b %s\n' "$C_CYAN" "$C_RESET" "$os_name" "$C_CYAN" "$C_RESET" "${gate:-"-"}"
  printf '%bPaketi:%b SSH %s | NGINX %s | PostgreSQL %s | Python %s\n' \
    "$C_CYAN" "$C_RESET" "$ssh_v" "$nginx_v" "$pg_v" "$py_v"
  printf '%bAction log:%b %s\n' "$C_CYAN" "$C_RESET" "$ACTION_LOG_FILE"
  printf '%b%s%b\n' "$C_BLUE$C_BOLD" "$line" "$C_RESET"
}

ui_begin() {
  local title="$1"
  clear || true
  render_header
  if command -v tput >/dev/null 2>&1; then
    tput csr "$HEADER_LINES" "$(($(term_lines) - 1))" 2>/dev/null || true
    tput cup "$HEADER_LINES" 0 2>/dev/null || true
  fi
  printf '%b%s%b\n\n' "$C_BOLD$C_WHITE" "$title" "$C_RESET"
}

menu_select() {
  local title="$1"
  shift
  local options=("$@")
  local selected=0
  local key idx

  while true; do
    ui_begin "$title" >&2
    for idx in "${!options[@]}"; do
      if [ "$idx" -eq "$selected" ]; then
        printf '%b > %s%b\n' "$C_SELECT$C_WHITE" "${options[$idx]}" "$C_RESET" >&2
      else
        printf '   %s\n' "${options[$idx]}" >&2
      fi
    done
    printf '\n%bStrelice gore/dolje%b za odabir, %bEnter%b za potvrdu.\n' "$C_DIM" "$C_RESET" "$C_BOLD" "$C_RESET" >&2
    IFS= read -rsn1 key
    case "$key" in
      "") printf '%s\n' "$selected"; return 0 ;;
      $'\x1b')
        IFS= read -rsn2 key || true
        case "$key" in
          "[A") [ "$selected" -gt 0 ] && selected=$((selected - 1)) ;;
          "[B") [ "$selected" -lt $((${#options[@]} - 1)) ] && selected=$((selected + 1)) ;;
        esac
        ;;
      k) [ "$selected" -gt 0 ] && selected=$((selected - 1)) ;;
      j) [ "$selected" -lt $((${#options[@]} - 1)) ] && selected=$((selected + 1)) ;;
    esac
  done
}

menu_select_with_context() {
  local title="$1"
  local context_fn="$2"
  shift 2
  local options=("$@")
  local selected=0
  local key idx

  while true; do
    ui_begin "$title" >&2
    "$context_fn" >&2 || true
    printf '\n' >&2
    for idx in "${!options[@]}"; do
      if [ "$idx" -eq "$selected" ]; then
        printf '%b > %s%b\n' "$C_SELECT$C_WHITE" "${options[$idx]}" "$C_RESET" >&2
      else
        printf '   %s\n' "${options[$idx]}" >&2
      fi
    done
    printf '\n%bStrelice gore/dolje%b za odabir, %bEnter%b za potvrdu.\n' "$C_DIM" "$C_RESET" "$C_BOLD" "$C_RESET" >&2
    IFS= read -rsn1 key
    case "$key" in
      "") printf '%s\n' "$selected"; return 0 ;;
      $'\x1b')
        IFS= read -rsn2 key || true
        case "$key" in
          "[A") [ "$selected" -gt 0 ] && selected=$((selected - 1)) ;;
          "[B") [ "$selected" -lt $((${#options[@]} - 1)) ] && selected=$((selected + 1)) ;;
        esac
        ;;
      k) [ "$selected" -gt 0 ] && selected=$((selected - 1)) ;;
      j) [ "$selected" -lt $((${#options[@]} - 1)) ] && selected=$((selected + 1)) ;;
    esac
  done
}

require_ubuntu() {
  if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    case "${ID:-}" in
      ubuntu|debian) return 0 ;;
      *) warn "Detektiran je ${PRETTY_NAME:-nepoznat OS}. Alat je ciljan za Ubuntu/Debian." ;;
    esac
  fi
}

ssh_config_file() {
  [ -f /etc/ssh/sshd_config ] && printf '%s\n' /etc/ssh/sshd_config || printf '%s\n' /etc/ssh/ssh_config
}

ssh_main_setting() {
  local key="$1" default="$2" cfg value
  cfg="$(ssh_config_file)"
  value="$(awk -v k="$key" -v d="$default" '
    BEGIN {IGNORECASE=1}
    /^[[:space:]]*Match[[:space:]]/ {exit}
    /^[[:space:]]*#/ {next}
    tolower($1)==tolower(k) {val=$2}
    END {print val ? val : d}
  ' "$cfg")"
  printf '%s\n' "$value"
}

ssh_root_login_state() {
  ssh_main_setting "PermitRootLogin" "yes"
}

ssh_password_auth_state() {
  ssh_main_setting "PasswordAuthentication" "yes"
}

has_non_root_shell_user() {
  awk -F: '$1 != "root" && $7 !~ /(nologin|false)$/ {found=1} END {exit found ? 0 : 1}' /etc/passwd
}

has_sudo_user() {
  getent group sudo 2>/dev/null | awk -F: 'NF >= 4 && $4 != "" {print "yes"}' | grep -q '^yes$'
}

ufw_is_active() {
  command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | head -n 1 | grep -qi 'Status: active'
}

ufw_status_output() {
  command -v ufw >/dev/null 2>&1 || return 1
  ufw status verbose 2>/dev/null || true
}

ufw_default_is_good() {
  local direction="$1" expected="$2" line
  line="$(ufw_status_output | grep -i '^Default:' || true)"
  printf '%s\n' "$line" | grep -Eiq "${expected}[[:space:]]+\(${direction}\)"
}

ufw_rule_allows() {
  local port="$1"
  command -v ufw >/dev/null 2>&1 || return 1
  ufw status 2>/dev/null | grep -Eiq "^${port}(/tcp)?[[:space:]]+ALLOW"
}

ufw_status_panel() {
  local status default_line rules
  if ! command -v ufw >/dev/null 2>&1; then
    printf '%bInstalled:%b no\n' "$C_RED$C_BOLD" "$C_RESET"
    printf '%bProblem:%b UFW nije instaliran. Firewall baseline se ne moze primijeniti.\n' "$C_RED" "$C_RESET"
    printf '%bPrijedlog:%b instaliraj UFW i primijeni baseline prije izlaganja servisa javnom internetu.\n' "$C_YELLOW" "$C_RESET"
    return 0
  fi

  status="$(ufw status 2>/dev/null | head -n 1 || true)"
  default_line="$(ufw_status_output | grep -i '^Default:' || true)"
  rules="$(ufw status 2>/dev/null | sed '1,4d' || true)"

  printf '%bInstalled:%b yes (%s)\n' "$C_GREEN" "$C_RESET" "$(package_version ufw)"
  if printf '%s\n' "$status" | grep -qi 'active'; then
    printf '%bStatus:%b active\n' "$C_GREEN" "$C_RESET"
  else
    printf '%bStatus:%b inactive\n' "$C_RED$C_BOLD" "$C_RESET"
  fi

  if [ -n "$default_line" ]; then
    if ufw_default_is_good "incoming" "deny"; then
      printf '%bDefault incoming:%b deny\n' "$C_GREEN" "$C_RESET"
    else
      printf '%bDefault incoming:%b %s\n' "$C_RED$C_BOLD" "$C_RESET" "$default_line"
    fi
    if ufw_default_is_good "outgoing" "allow"; then
      printf '%bDefault outgoing:%b allow\n' "$C_GREEN" "$C_RESET"
    else
      printf '%bDefault outgoing:%b %s\n' "$C_RED$C_BOLD" "$C_RESET" "$default_line"
    fi
  else
    printf '%bDefault policies:%b nije moguce procitati bez dodatnih prava ili UFW nije inicijaliziran.\n' "$C_YELLOW" "$C_RESET"
  fi

  printf '\n%bOsnovna pravila:%b\n' "$C_CYAN" "$C_RESET"
  for port in 22 80 443; do
    if ufw_rule_allows "$port"; then
      printf '  %bALLOW %s/tcp%b\n' "$C_GREEN" "$port" "$C_RESET"
    else
      printf '  %bMISSING allow %s/tcp%b\n' "$C_RED$C_BOLD" "$port" "$C_RESET"
    fi
  done

  printf '\n%bPostojeca UFW pravila:%b\n' "$C_CYAN" "$C_RESET"
  if [ -n "$rules" ]; then
    printf '%s\n' "$rules" | sed '/^[[:space:]]*$/d' | head -n 12
  else
    printf '  - nema pravila ili ih nije moguce procitati\n'
  fi

  printf '\n%bPrijedlozi:%b\n' "$C_YELLOW" "$C_RESET"
  printf '%s\n' "$status" | grep -qi 'active' || printf '  - Enable UFW nakon sto je SSH port dozvoljen, inace mozes izgubiti pristup.\n'
  ufw_default_is_good "incoming" "deny" || printf '  - Postavi default deny incoming.\n'
  ufw_default_is_good "outgoing" "allow" || printf '  - Postavi default allow outgoing.\n'
  ufw_rule_allows 22 || printf '  - Dozvoli 22/tcp prije enable koraka ako SSH koristis za pristup serveru.\n'
  ufw_rule_allows 80 || printf '  - Dozvoli 80/tcp ako server treba HTTP.\n'
  ufw_rule_allows 443 || printf '  - Dozvoli 443/tcp ako server treba HTTPS.\n'
}

nginx_is_installed() {
  dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -q "install ok installed"
}

backup_jobs_count() {
  find /etc/cron.d -maxdepth 1 -type f -name 'ubuntuav-*' 2>/dev/null | wc -l | tr -d ' '
}

security_recommendation_count() {
  local count=0
  [ "$(ssh_root_login_state)" != "no" ] && count=$((count + 1))
  [ "$(ssh_password_auth_state)" = "yes" ] && count=$((count + 1))
  ufw_is_active || count=$((count + 1))
  printf '%s\n' "$count"
}

web_recommendation_count() {
  local count=0
  if nginx_is_installed && [ ! -f /etc/nginx/snippets/ubuntuav-rate-limit-location.conf ]; then
    count=$((count + 1))
  fi
  printf '%s\n' "$count"
}

operations_recommendation_count() {
  local count=0
  [ "$(backup_jobs_count)" -eq 0 ] && count=$((count + 1))
  printf '%s\n' "$count"
}

ssh_recommendations() {
  local root_state pass_state
  root_state="$(ssh_root_login_state)"
  pass_state="$(ssh_password_auth_state)"
  printf '%bStatus:%b PermitRootLogin=%s | PasswordAuthentication=%s\n' "$C_CYAN" "$C_RESET" "$root_state" "$pass_state"
  if has_non_root_shell_user; then
    printf '%bCheck:%b postoji barem jedan non-root shell user.\n' "$C_GREEN" "$C_RESET"
  else
    printf '%bRisk:%b ne postoji nijedan non-root shell user. Ne gasi root login dok ne kreiras admin user.\n' "$C_RED" "$C_RESET"
  fi
  if has_sudo_user; then
    printf '%bCheck:%b postoji barem jedan sudo korisnik.\n' "$C_GREEN" "$C_RESET"
  else
    printf '%bRisk:%b sudo grupa nema korisnika. Prvo osiguraj admin pristup prije hardeninga.\n' "$C_RED" "$C_RESET"
  fi
  [ "$root_state" = "no" ] || printf '%bBest practice:%b ugasi root remote login nakon sto potvrdis alternativni admin pristup.\n' "$C_YELLOW" "$C_RESET"
  [ "$pass_state" != "yes" ] || printf '%bBest practice:%b ugasi globalni password auth ili ga ograniciti samo na trusted mreze.\n' "$C_YELLOW" "$C_RESET"
}

backup_file() {
  local file="$1"
  if [ ! -e "$file" ]; then
    warn "Datoteka ne postoji, backup preskocen: $file"
    return 0
  fi
  local dir base dest
  dir="$(dirname "$file")"
  base="$(basename "$file")"
  dest="$dir/$(timestamp).$base"
  run_root cp -a "$file" "$dest"
  info "Backup: $dest"
}

safe_append_once() {
  local file="$1" marker="$2" content="$3"
  if [ -f "$file" ] && grep -Fq "$marker" "$file"; then
    info "Blok vec postoji u $file"
    return 0
  fi
  backup_file "$file"
  printf '%s\n' "$content" | run_root tee -a "$file" >/dev/null
  log_comment "Append managed block to $file"
  log_append_file "$file" "$content"
}

download_file() {
  local url="$1" output="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL -o "$output" "$url"
  elif command -v wget >/dev/null 2>&1; then
    wget -O "$output" "$url"
  else
    err "Ni curl ni wget nisu dostupni za download."
    return 1
  fi
}

install_packages() {
  local packages=("$@")
  [ "${#packages[@]}" -eq 0 ] && return 0
  info "Paketi za instalaciju: ${packages[*]}"
  confirm "Instalirati apt pakete?" || return 0
  log_comment "Install packages: ${packages[*]}"
  log_action "sudo apt-get update"
  log_action "sudo apt-get install -y ${packages[*]}"
  run_root apt-get update
  run_root apt-get install -y "${packages[@]}"
}

service_restart() {
  local svc="$1"
  if confirm "Restartati servis $svc?"; then
    log_comment "Restart service $svc"
    log_action "sudo systemctl restart $svc"
    run_root systemctl restart "$svc"
  fi
}

print_cmd() {
  local title="$1"
  shift
  printf '%b%s%b\n' "$C_BOLD$C_WHITE" "$title" "$C_RESET"
  if "$@"; then :; else warn "Naredba nije uspjela: $*"; fi
  printf '\n'
}

main_menu() {
  while true; do
    local choice overview_item security_item web_item data_item ops_item
    overview_item="$(menu_badge "Pregled i inventar" 0)"
    security_item="$(menu_badge "Pristup i sigurnost" "$(security_recommendation_count)")"
    web_item="$(menu_badge "Web stack" "$(web_recommendation_count)")"
    data_item="$(menu_badge "Baze i runtime" 0)"
    ops_item="$(menu_badge "Operacije i backup" "$(operations_recommendation_count)")"
    choice="$(menu_select "Glavni izbornik" \
      "$overview_item" \
      "$security_item" \
      "$web_item" \
      "$data_item" \
      "$ops_item" \
      "GitHub deploy helper" \
      "Backups list / restore" \
      "Exit")"
    case "$choice" in
      0) menu_overview ;;
      1) menu_security ;;
      2) menu_web_stack ;;
      3) menu_data_runtime ;;
      4) menu_operations ;;
      5) menu_github_deploy ;;
      6) menu_backups ;;
      7) exit 0 ;;
    esac
  done
}

menu_overview() {
  while true; do
    local c
    c="$(menu_select "Pregled i inventar" "System overview" "Backups list / restore" "Nazad")"
    case "$c" in
      0) system_overview ;;
      1) menu_backups ;;
      2) return ;;
    esac
  done
}

menu_security() {
  while true; do
    local c ssh_item ufw_item ssh_count
    ssh_count=0
    [ "$(ssh_root_login_state)" != "no" ] && ssh_count=$((ssh_count + 1))
    [ "$(ssh_password_auth_state)" = "yes" ] && ssh_count=$((ssh_count + 1))
    ssh_item="$(menu_badge "SSH" "$ssh_count")"
    if ufw_is_active; then
      ufw_item="UFW firewall"
    else
      ufw_item="$(menu_badge "UFW firewall" 1)"
    fi
    c="$(menu_select "Pristup i sigurnost" "ZeroTier" "$ssh_item" "$ufw_item" "AppArmor" "Nazad")"
    case "$c" in
      0) menu_zerotier ;;
      1) menu_ssh ;;
      2) menu_ufw ;;
      3) menu_apparmor ;;
      4) return ;;
    esac
  done
}

menu_web_stack() {
  while true; do
    local c
    c="$(menu_select "Web stack" "NGINX" "NGINX GeoIP2" "NGINX rate limiting" "SSL / OpenSSL / certbot" "Webmin" "Nazad")"
    case "$c" in
      0) menu_nginx ;;
      1) menu_geoip2 ;;
      2) menu_rate_limit ;;
      3) menu_ssl ;;
      4) menu_webmin ;;
      5) return ;;
    esac
  done
}

menu_data_runtime() {
  while true; do
    local c
    c="$(menu_select "Baze i runtime" "PostgreSQL" "Python" "Nazad")"
    case "$c" in
      0) menu_postgresql ;;
      1) menu_python ;;
      2) return ;;
    esac
  done
}

menu_operations() {
  while true; do
    local c
    c="$(menu_select "Operacije i backup" "Backup" "System tools / Telegram / Disk / SpeedTest" "Nazad")"
    case "$c" in
      0) menu_backup ;;
      1) menu_system_tools ;;
      2) return ;;
    esac
  done
}

system_overview() {
  ui_begin "System overview"
  print_cmd "Hostname" hostnamectl
  print_cmd "Uptime" uptime
  print_cmd "IP adrese" ip -br addr
  print_cmd "Gateway / route" ip route
  print_cmd "DNS" resolvectl status
  print_cmd "Network adapteri" ip -details link
  print_cmd "Disk" df -hT
  print_cmd "Memory" free -h
  pause
}

menu_zerotier() {
  while true; do
    local c
    c="$(menu_select "ZeroTier" "Instaliraj ZeroTier" "Status / info" "Join network" "Leave network" "List networks" "List peers" "Nazad")"
    case "$c" in
      0) install_packages curl gnupg; curl -s https://install.zerotier.com | run_root bash ;;
      1) ui_begin "ZeroTier status"; run_root zerotier-cli info; pause ;;
      2) id="$(prompt_value "ZeroTier network ID")"; [ -n "$id" ] && run_root zerotier-cli join "$id"; pause ;;
      3) id="$(prompt_value "ZeroTier network ID")"; [ -n "$id" ] && run_root zerotier-cli leave "$id"; pause ;;
      4) ui_begin "ZeroTier networks"; run_root zerotier-cli listnetworks; pause ;;
      5) ui_begin "ZeroTier peers"; run_root zerotier-cli peers; pause ;;
      6) return ;;
    esac
  done
}

menu_nginx() {
  while true; do
    local c
    c="$(menu_select "NGINX" "Instaliraj NGINX" "Ispisi konfiguraciju i siteove" "Test konfiguracije" "Dodaj basic website" "Ukloni enabled website" "Restart / reload" "Nazad")"
    case "$c" in
      0) install_packages nginx ;;
      1) nginx_show_config ;;
      2) ui_begin "NGINX test"; run_root nginx -t; pause ;;
      3) nginx_add_site ;;
      4) nginx_remove_site ;;
      5) confirm "Reload NGINX?" && run_root systemctl reload nginx; pause ;;
      6) return ;;
    esac
  done
}

detect_webservers() {
  print_cmd "Webserver procesi/servisi" bash -lc '
    for svc in nginx apache2 lighttpd caddy; do
      if systemctl list-unit-files "$svc.service" >/dev/null 2>&1; then
        systemctl is-active "$svc" >/dev/null 2>&1 && printf "%s: active\n" "$svc" || printf "%s: installed/inactive\n" "$svc"
      fi
    done
    ss -tulpn 2>/dev/null | grep -E ":(80|443)\s" || true
  '
}

nginx_show_config() {
  ui_begin "NGINX konfiguracija"
  detect_webservers
  run_root nginx -T 2>/tmp/ubuntuav-nginx.txt || true
  less /tmp/ubuntuav-nginx.txt || cat /tmp/ubuntuav-nginx.txt
  pause
}

nginx_add_site() {
  local domain root conf body
  domain="$(prompt_value "Domena/site name")"
  [ -n "$domain" ] || return 0
  root="/var/www/$domain/public"
  conf="/etc/nginx/sites-available/$domain"
  body=$(cat <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $domain;
    root $root;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
)
  ui_begin "NGINX new site"
  info "Kreiram $root i $conf"
  confirm "Nastaviti?" || return 0
  log_comment "Create NGINX site $domain"
  log_action "sudo mkdir -p $root"
  run_root mkdir -p "$root"
  printf '<h1>%s</h1>\n' "$domain" | run_root tee "$root/index.html" >/dev/null
  [ -e "$conf" ] && backup_file "$conf"
  printf '%s\n' "$body" | run_root tee "$conf" >/dev/null
  log_write_file "$root/index.html" "<h1>$domain</h1>"
  log_write_file "$conf" "$body"
  log_action "sudo ln -sfn $conf /etc/nginx/sites-enabled/$domain"
  run_root ln -sfn "$conf" "/etc/nginx/sites-enabled/$domain"
  run_root nginx -t && service_restart nginx
  pause
}

nginx_remove_site() {
  ui_begin "NGINX remove site"
  ls -1 /etc/nginx/sites-enabled 2>/dev/null || true
  local site target
  site="$(prompt_value "Enabled site za ukloniti")"
  [ -n "$site" ] || return 0
  target="/etc/nginx/sites-enabled/$site"
  if [ -e "$target" ] || [ -L "$target" ]; then
    if confirm "Maknuti symlink $target?"; then
      log_comment "Remove NGINX enabled site $site"
      log_action "sudo rm $target"
      run_root rm "$target"
    fi
  fi
  run_root nginx -t && service_restart nginx
  pause
}

menu_geoip2() {
  while true; do
    local c
    c="$(menu_select "NGINX GeoIP2" "Instaliraj modul" "Dodaj globalni GeoIP2 EU map snippet" "Dodaj site allow/deny snippet primjer" "Test NGINX" "Nazad")"
    case "$c" in
      0) install_packages libnginx-mod-http-geoip2 geoipupdate ;;
      1) geoip2_global_snippet ;;
      2) geoip2_site_snippet ;;
      3) ui_begin "NGINX GeoIP2 test"; run_root nginx -t; pause ;;
      4) return ;;
    esac
  done
}

geoip2_global_snippet() {
  local file="/etc/nginx/conf.d/ubuntuav-geoip2.conf" maps="" cc content
  for cc in $EU_COUNTRIES; do
    maps="${maps}    ${cc} 1;\n"
  done
  content=$(printf '%s\ngeoip2 /usr/share/GeoIP/GeoLite2-Country.mmdb {\n    $geoip2_data_country_code country iso_code;\n}\n\nmap $geoip2_data_country_code $is_eu {\n    default 0;\n%b}\n' "$MANAGED_MARK" "$maps")
  safe_append_once "$file" "$MANAGED_MARK" "$content"
  ui_begin "NGINX GeoIP2"
  run_root nginx -t
  pause
}

geoip2_site_snippet() {
  local file="/etc/nginx/snippets/ubuntuav-geoip2-site-policy.conf" content
  content=$(cat <<'EOF'
# ubuntuAV managed
# Include inside server/location block, then customize as needed.
# if ($geoip2_data_country_code ~ (CN|RU)) { return 403; }
# if ($geoip2_data_country_code != "HR") { return 403; }
if ($is_eu = 0) {
    return 403;
}
EOF
)
  safe_append_once "$file" "$MANAGED_MARK" "$content"
  ui_begin "NGINX GeoIP2"
  info "U site dodaj: include snippets/ubuntuav-geoip2-site-policy.conf;"
  pause
}

menu_rate_limit() {
  ui_begin "NGINX rate limiting"
  local global="/etc/nginx/conf.d/ubuntuav-rate-limit.conf"
  local snippet="/etc/nginx/snippets/ubuntuav-rate-limit-location.conf"
  local gcontent="$MANAGED_MARK
limit_req_zone \$binary_remote_addr zone=req_limit:10m rate=5r/s;"
  local scontent="$MANAGED_MARK
limit_req zone=req_limit burst=10 nodelay;"
  confirm "Dodati globalni req_limit i location snippet?" || return 0
  safe_append_once "$global" "$MANAGED_MARK" "$gcontent"
  safe_append_once "$snippet" "$MANAGED_MARK" "$scontent"
  info "U zeljeni location dodaj: include snippets/ubuntuav-rate-limit-location.conf;"
  run_root nginx -t
  pause
}

menu_apparmor() {
  while true; do
    local c p
    c="$(menu_select "AppArmor" "Enforce profile" "Complain profile" "Reload AppArmor" "Nazad")"
    case "$c" in
      0) p="$(prompt_value "Profile path/name")"; [ -n "$p" ] && run_root aa-enforce "$p"; pause ;;
      1) p="$(prompt_value "Profile path/name")"; [ -n "$p" ] && run_root aa-complain "$p"; pause ;;
      2) run_root systemctl reload apparmor; pause ;;
      3) return ;;
    esac
  done
}

menu_ssl() {
  while true; do
    local c d
    c="$(menu_select "SSL / certbot" "OpenSSL self-signed cert" "Instaliraj certbot NGINX plugin" "Izradi/obnovi Let's Encrypt cert za domenu" "Test renewal" "Nazad")"
    case "$c" in
      0) ssl_self_signed ;;
      1) install_packages certbot python3-certbot-nginx ;;
      2) d="$(prompt_value "Domena")"; [ -n "$d" ] && run_root certbot --nginx -d "$d"; pause ;;
      3) ui_begin "certbot renew"; run_root certbot renew --dry-run; pause ;;
      4) return ;;
    esac
  done
}

ssl_self_signed() {
  local domain dir
  domain="$(prompt_value "Domena/CN")"
  [ -n "$domain" ] || return 0
  dir="/etc/ssl/ubuntuav/$domain"
  run_root mkdir -p "$dir"
  run_root openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "$dir/privkey.pem" -out "$dir/fullchain.pem" -subj "/CN=$domain"
  ui_begin "SSL"
  info "Cert: $dir/fullchain.pem"
  pause
}

menu_ssh() {
  while true; do
    local c root_state pass_state
    root_state="$(ssh_root_login_state)"
    pass_state="$(ssh_password_auth_state)"
    c="$(menu_select "SSH" \
      "Status i preporuke" \
      "Disable root login [trenutno: $root_state]" \
      "Disable global password authentication [trenutno: $pass_state]" \
      "Dodaj ZeroTier subnet Match rule za password auth" \
      "Test sshd config" \
      "Restart SSH" \
      "Nazad")"
    case "$c" in
      0) ui_begin "SSH status i preporuke"; ssh_audit; printf '\n'; ssh_recommendations; pause ;;
      1) ssh_disable_root_login ;;
      2) ssh_set_option PasswordAuthentication no ;;
      3) ssh_zt_password_rule ;;
      4) ui_begin "sshd test"; run_root sshd -t; pause ;;
      5) service_restart ssh; pause ;;
      6) return ;;
    esac
  done
}

ssh_audit() {
  local cfg
  cfg="$(ssh_config_file)"
  printf 'Config: %s\n' "$cfg"
  grep -Ei '^(PermitRootLogin|PasswordAuthentication|KbdInteractiveAuthentication|PubkeyAuthentication|AllowUsers|Match)' "$cfg" || true
  printf '\nKorisnici s shell pristupom:\n'
  awk -F: '$7 !~ /(nologin|false)$/ {print $1 " -> " $7}' /etc/passwd
  printf '\nAuthorized keys:\n'
  find /home /root -maxdepth 3 -name authorized_keys -type f -printf '%p\n' 2>/dev/null || true
}

ssh_disable_root_login() {
  ui_begin "SSH root login hardening"
  ssh_audit
  printf '\n'
  ssh_recommendations
  if ! has_non_root_shell_user; then
    err "Nema non-root shell usera. Prvo kreiraj admin korisnika."
    pause
    return 1
  fi
  if ! has_sudo_user; then
    err "Nema korisnika u sudo grupi. Prvo osiguraj admin pristup."
    pause
    return 1
  fi
  ssh_set_option PermitRootLogin no
}

ssh_set_option() {
  local key="$1" val="$2" cfg
  cfg="$(ssh_config_file)"
  ui_begin "SSH konfiguracija"
  ssh_audit
  confirm "Postaviti $key $val u $cfg?" || return 0
  backup_file "$cfg"
  if grep -Eq "^[#[:space:]]*$key[[:space:]]+" "$cfg"; then
    log_comment "Set $key $val in $cfg"
    log_action "sudo sed -i -E 's|^[#[:space:]]*$key[[:space:]]+.*|$key $val|' $cfg"
    run_root sed -i -E "s|^[#[:space:]]*$key[[:space:]]+.*|$key $val|" "$cfg"
  else
    log_comment "Append $key $val to $cfg"
    log_action "printf '%s %s\\n' '$key' '$val' | sudo tee -a $cfg >/dev/null"
    printf '%s %s\n' "$key" "$val" | run_root tee -a "$cfg" >/dev/null
  fi
  run_root sshd -t
  pause
}

ssh_zt_password_rule() {
  local cfg subnet block
  cfg="$(ssh_config_file)"
  subnet="$(prompt_value "ZeroTier subnet/CIDR koji smije password auth (npr 10.147.0.0/16)")"
  [ -n "$subnet" ] || return 0
  block="$MANAGED_MARK
Match Address $subnet
    PasswordAuthentication yes"
  safe_append_once "$cfg" "$MANAGED_MARK" "$block"
  log_comment "Add ZeroTier password auth match rule for $subnet"
  ui_begin "SSH konfiguracija"
  run_root sshd -t
  pause
}

menu_ufw() {
  while true; do
    local c p
    c="$(menu_select_with_context "UFW firewall" ufw_status_panel "Primijeni baseline: deny incoming, allow outgoing, allow 22/80/443" "Allow port" "Deny port" "Enable UFW" "Disable UFW" "Nazad")"
    case "$c" in
      0) ufw_baseline ;;
      1) p="$(prompt_value "Port/protocol (npr 5432/tcp)")"; ufw_allow_port "$p" ;;
      2) p="$(prompt_value "Port/protocol")"; ufw_deny_port "$p" ;;
      3) ufw_enable ;;
      4) ufw_disable ;;
      5) return ;;
    esac
  done
}

ufw_allow_port() {
  local port="$1"
  [ -n "$port" ] || return 0
  log_comment "UFW allow $port"
  log_action "sudo ufw allow $port"
  run_root ufw allow "$port"
  pause
}

ufw_deny_port() {
  local port="$1"
  [ -n "$port" ] || return 0
  log_comment "UFW deny $port"
  log_action "sudo ufw deny $port"
  run_root ufw deny "$port"
  pause
}

ufw_enable() {
  log_comment "Enable UFW"
  log_action "sudo ufw enable"
  run_root ufw enable
  pause
}

ufw_disable() {
  log_comment "Disable UFW"
  log_action "sudo ufw disable"
  run_root ufw disable
  pause
}

ufw_baseline() {
  ui_begin "UFW baseline"
  confirm "Primijeniti UFW baseline pravila?" || return 0
  log_comment "Apply UFW baseline"
  log_action "sudo ufw default deny incoming"
  log_action "sudo ufw default allow outgoing"
  log_action "sudo ufw allow 22/tcp"
  log_action "sudo ufw allow 80/tcp"
  log_action "sudo ufw allow 443/tcp"
  run_root ufw default deny incoming
  run_root ufw default allow outgoing
  run_root ufw allow 22/tcp
  run_root ufw allow 80/tcp
  run_root ufw allow 443/tcp
  run_root ufw status verbose
  pause
}

menu_webmin() {
  ui_begin "Webmin"
  if command -v webmin >/dev/null 2>&1 || systemctl list-unit-files webmin.service >/dev/null 2>&1; then
    run_root systemctl status webmin --no-pager || true
  else
    warn "Webmin nije detektiran."
  fi
  webmin_cleanup_repositories
  confirm "Instalirati Webmin .deb paket bez Webmin APT repoa?" || { pause; return; }
  install_packages ca-certificates
  webmin_install_deb
  run_root apt-get update
  if command -v ufw >/dev/null 2>&1 && confirm "Otvoriti UFW port 10000/tcp za Webmin?"; then
    run_root ufw allow 10000/tcp
  fi
  pause
}

webmin_cleanup_repositories() {
  local legacy_repo="/etc/apt/sources.list.d/webmin.list"
  local managed_repo="/etc/apt/sources.list.d/webmin-stable.list"
  if [ -f "$legacy_repo" ]; then
    backup_file "$legacy_repo"
    log_comment "Remove legacy Webmin repo $legacy_repo"
    log_action "sudo rm -f $legacy_repo"
    run_root rm -f "$legacy_repo"
  fi
  if [ -f "$managed_repo" ]; then
    backup_file "$managed_repo"
    log_comment "Remove managed Webmin repo $managed_repo"
    log_action "sudo rm -f $managed_repo"
    run_root rm -f "$managed_repo"
  fi
}

webmin_install_deb() {
  local package="/tmp/webmin-current.deb"
  log_comment "Install Webmin from .deb package"
  log_action "curl -fsSL -o $package https://www.webmin.com/download/deb/webmin-current.deb"
  log_action "sudo apt-get install -y --install-recommends $package"
  download_file "https://www.webmin.com/download/deb/webmin-current.deb" "$package"
  run_root apt-get install -y --install-recommends "$package"
  rm -f "$package"
}

menu_postgresql() {
  while true; do
    local c
    c="$(menu_select "PostgreSQL" "Instaliraj PostgreSQL" "List users/databases" "Show memory settings" "Create dump task primjer" "Replication setup checklist" "Nazad")"
    case "$c" in
      0) install_packages postgresql postgresql-contrib ;;
      1) ui_begin "PostgreSQL users/databases"; run_user postgres psql -c '\du'; run_user postgres psql -c '\l'; pause ;;
      2) ui_begin "PostgreSQL memory"; run_user postgres psql -c "show shared_buffers; show effective_cache_size; show work_mem; show maintenance_work_mem;"; pause ;;
      3) pg_dump_task ;;
      4) pg_replication_checklist ;;
      5) return ;;
    esac
  done
}

pg_audit() {
  command -v psql >/dev/null 2>&1 && psql --version || warn "PostgreSQL klijent nije instaliran."
  command -v pg_lsclusters >/dev/null 2>&1 && pg_lsclusters || true
}

pg_dump_task() {
  local db dir script content
  db="$(prompt_value "Database name")"
  [ -n "$db" ] || return 0
  dir="$(prompt_value "Backup dir [/var/backups/postgresql]")"
  dir="${dir:-/var/backups/postgresql}"
  script="/usr/local/sbin/ubuntuav-pg-dump-$db.sh"
  content="#!/usr/bin/env bash
set -Eeuo pipefail
mkdir -p '$dir'
pg_dump -Fc '$db' > '$dir/$db-\$(date +%Y%m%d-%H%M%S).dump'"
  confirm "Kreirati $script i cron dnevno u 02:30?" || return 0
  log_comment "Create PostgreSQL dump task for $db"
  printf '%s\n' "$content" | run_root tee "$script" >/dev/null
  log_write_file "$script" "$content"
  run_root chmod +x "$script"
  printf '30 2 * * * postgres %s\n' "$script" | run_root tee "/etc/cron.d/ubuntuav-pg-dump-$db" >/dev/null
  log_write_file "/etc/cron.d/ubuntuav-pg-dump-$db" "30 2 * * * postgres $script"
  pause
}

pg_replication_checklist() {
  ui_begin "PostgreSQL replication checklist"
  cat <<'TEXT'
1. Primary: postavi wal_level=replica, max_wal_senders i hot_standby=on.
2. Primary: kreiraj replication user sa jakom lozinkom.
3. Primary: dodaj standby IP u pg_hba.conf za replication.
4. Standby: pokreni pg_basebackup sa primary hosta.
5. Standby: kreiraj standby.signal i primary_conninfo.
6. Testiraj failover prije produkcije.
TEXT
  pause
}

menu_python() {
  while true; do
    local c p
    c="$(menu_select "Python" "Instaliraj python3/pip/venv" "Instaliraj specificni apt paket" "Ukloni apt python paket" "Nazad")"
    case "$c" in
      0) install_packages python3 python3-pip python3-venv ;;
      1) p="$(prompt_value "Package")"; [ -n "$p" ] && install_packages "$p" ;;
      2) p="$(prompt_value "Package za remove")"; [ -n "$p" ] && confirm "Ukloniti $p?" && run_root apt-get remove -y "$p"; pause ;;
      3) return ;;
    esac
  done
}

menu_backup() {
  while true; do
    local c
    c="$(menu_select "Backup" "Filesystem tar.gz backup task" "FTP upload task primjer" "PostgreSQL dump task" "List cron ubuntuAV tasks" "Nazad")"
    case "$c" in
      0) fs_backup_task ;;
      1) ftp_backup_task ;;
      2) pg_dump_task ;;
      3) ui_begin "ubuntuAV cron tasks"; ls -l /etc/cron.d/ubuntuav-* 2>/dev/null || true; pause ;;
      4) return ;;
    esac
  done
}

fs_backup_task() {
  local src dir name script content
  src="$(prompt_value "Path za backup")"
  [ -n "$src" ] || return 0
  dir="$(prompt_value "Backup dir [/var/backups/ubuntuav]")"
  dir="${dir:-/var/backups/ubuntuav}"
  name="$(basename "$src" | tr -c 'A-Za-z0-9_.-' '_')"
  script="/usr/local/sbin/ubuntuav-fs-backup-$name.sh"
  content="#!/usr/bin/env bash
set -Eeuo pipefail
mkdir -p '$dir'
tar -czf '$dir/$name-\$(date +%Y%m%d-%H%M%S).tar.gz' '$src'"
  confirm "Kreirati $script i cron dnevno u 03:00?" || return 0
  log_comment "Create filesystem backup task for $src"
  printf '%s\n' "$content" | run_root tee "$script" >/dev/null
  log_write_file "$script" "$content"
  run_root chmod +x "$script"
  printf '0 3 * * * root %s\n' "$script" | run_root tee "/etc/cron.d/ubuntuav-fs-backup-$name" >/dev/null
  log_write_file "/etc/cron.d/ubuntuav-fs-backup-$name" "0 3 * * * root $script"
  pause
}

ftp_backup_task() {
  ui_begin "FTP backup"
  cat <<'TEXT'
FTP preporuka:
- Nemoj spremati FTP lozinku u repo.
- Na serveru koristi /root/.netrc s chmod 600 ili SFTP/SSH key gdje je moguce.
- Script moze uploadati postojeci backup direktorij pomocu lftp mirror -R.
TEXT
  install_packages lftp
  pause
}

menu_system_tools() {
  while true; do
    local c
    c="$(menu_select "System tools" "Check updates" "Basic info" "Telegram test/send setup" "Disk/partitions" "Mount network disk guidance" "SpeedTest / fio" "Nazad")"
    case "$c" in
      0) ui_begin "APT updates"; run_root apt-get update; apt list --upgradable; pause ;;
      1) system_overview ;;
      2) telegram_setup ;;
      3) ui_begin "Disk/partitions"; lsblk -f; df -hT; pause ;;
      4) network_disk_guidance ;;
      5) speedtest_fio ;;
      6) return ;;
    esac
  done
}

telegram_setup() {
  ui_begin "Telegram"
  cat <<'TEXT'
1. Kod BotFather kreiraj bot i token spremi lokalno, ne u repo.
2. Dohvati chat_id slanjem poruke botu pa otvori getUpdates.
3. Preporuka: spremi /etc/ubuntuav/telegram.env s chmod 600:
   TELEGRAM_BOT_TOKEN=...
   TELEGRAM_CHAT_ID=...
TEXT
  confirm "Kreirati helper /usr/local/bin/ubuntuav-telegram-send?" || return 0
  run_root mkdir -p /etc/ubuntuav
  local helper="/usr/local/bin/ubuntuav-telegram-send"
  local content='#!/usr/bin/env bash
set -Eeuo pipefail
. /etc/ubuntuav/telegram.env
msg="${1:-ubuntuAV test}"
curl -fsS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
  -d "chat_id=${TELEGRAM_CHAT_ID}" \
  --data-urlencode "text=${msg}"'
  printf '%s\n' "$content" | run_root tee "$helper" >/dev/null
  log_comment "Create Telegram helper"
  log_write_file "$helper" "$content"
  run_root chmod +x "$helper"
  pause
}

network_disk_guidance() {
  ui_begin "Network disk guidance"
  cat <<'TEXT'
Network disk mapping:
- SMB/CIFS: apt install cifs-utils, credentials in /root/.smbcredentials chmod 600.
- NFS: apt install nfs-common, mount server:/export /mnt/name.
- Uvijek testiraj manualno prije dodavanja u /etc/fstab.
TEXT
  pause
}

speedtest_fio() {
  while true; do
    local c
    c="$(menu_select "SpeedTest / fio" "Instaliraj fio i speedtest-cli" "Run fio quick disk test" "Run network speedtest" "Nazad")"
    case "$c" in
      0) install_packages fio speedtest-cli ;;
      1) ui_begin "fio"; fio --name=ubuntuav --filename=/tmp/ubuntuav-fio-test --size=256M --rw=readwrite --bs=4k --iodepth=16 --runtime=30 --time_based --group_reporting; rm -f /tmp/ubuntuav-fio-test; pause ;;
      2) ui_begin "speedtest"; speedtest-cli; pause ;;
      3) return ;;
    esac
  done
}

menu_github_deploy() {
  while true; do
    local c key
    c="$(menu_select "GitHub deploy helper" "Generiraj deploy SSH key" "Ispisi public key" "Test git SSH prema GitHubu" "Nazad")"
    key="$HOME/.ssh/ubuntuav_github_deploy"
    case "$c" in
      0) log_comment "Generate GitHub deploy SSH key"; log_action "ssh-keygen -t ed25519 -C ubuntuav-deploy-\$(hostname) -f $key"; mkdir -p "$HOME/.ssh"; chmod 700 "$HOME/.ssh"; ssh-keygen -t ed25519 -C "ubuntuav-deploy-$(hostname)" -f "$key"; pause ;;
      1) ui_begin "GitHub deploy public key"; cat "$key.pub"; pause ;;
      2) ui_begin "GitHub SSH test"; ssh -T git@github.com || true; pause ;;
      3) return ;;
    esac
  done
}

menu_backups() {
  ui_begin "Backups list / restore"
  local file dir base backup
  file="$(prompt_value "Original file path za pretragu backupova")"
  [ -n "$file" ] || return 0
  dir="$(dirname "$file")"
  base="$(basename "$file")"
  ls -1 "$dir"/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]."$base" 2>/dev/null || true
  backup="$(prompt_value "Backup file za restore (prazno za nazad)")"
  [ -n "$backup" ] || return 0
  [ -f "$backup" ] || { warn "Ne postoji: $backup"; pause; return 1; }
  confirm "Restore $backup -> $file?" || return 0
  backup_file "$file"
  run_root cp -a "$backup" "$file"
  pause
}

init_action_log
require_ubuntu
main_menu
